apiVersion: v1
kind: Pod
metadata:
  name: website
  labels:
    app: website
    tier: frontend
spec:
  containers:
  - name: git-sync
    image: gcr.io/google_containers/git-sync
    imagePullPolicy: Always
    volumeMounts:
    - name: www
      mountPath: /git
    env:
    - name: GIT_SYNC_REPO
      value: https://github.com/VikramTiwari/vikramtiwari.github.com.git
    - name: GIT_SYNC_DEST
      value: git
    - name: GIT_SYNC_WAIT
      value: "10"
  - name: nginx
    image: nginx
    volumeMounts:
    - name: www
      mountPath: /usr/share/nginx/html
      readOnly: true
    ports:
    - containerPort: 80
    - containerPort: 443
  volumes:
  - name: www
    emptyDir: {}
